// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUh19PA4unA0JGt0j85nUoF5ZTH1x5E4s',
    appId: '1:15740485843:web:339c8b0aed53376cd15426',
    messagingSenderId: '15740485843',
    projectId: 'calorie-calculator-40ou',
    authDomain: 'calorie-calculator-40ou.firebaseapp.com',
    storageBucket: 'calorie-calculator-40ou.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDm6fd7kxSCAJBCDDYr4gXwPaAbE2POxyE',
    appId: '1:15740485843:android:14f28d7bf81dd4f3d15426',
    messagingSenderId: '15740485843',
    projectId: 'calorie-calculator-40ou',
    storageBucket: 'calorie-calculator-40ou.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGMnAdj92WiIIhctghtD-eP8NlliSeuuk',
    appId: '1:15740485843:ios:42b2eeab28aa0081d15426',
    messagingSenderId: '15740485843',
    projectId: 'calorie-calculator-40ou',
    storageBucket: 'calorie-calculator-40ou.appspot.com',
    iosClientId:
        '15740485843-n9dvfrkqdur0ka7juuvpv372s4gfdklh.apps.googleusercontent.com',
    iosBundleId: 'com.example.caloriesCalculator',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGMnAdj92WiIIhctghtD-eP8NlliSeuuk',
    appId: '1:15740485843:ios:42b2eeab28aa0081d15426',
    messagingSenderId: '15740485843',
    projectId: 'calorie-calculator-40ou',
    storageBucket: 'calorie-calculator-40ou.appspot.com',
    iosClientId:
        '15740485843-n9dvfrkqdur0ka7juuvpv372s4gfdklh.apps.googleusercontent.com',
    iosBundleId: 'com.example.caloriesCalculator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUh19PA4unA0JGt0j85nUoF5ZTH1x5E4s',
    appId: '1:15740485843:web:b44e762557cbaf61d15426',
    messagingSenderId: '15740485843',
    projectId: 'calorie-calculator-40ou',
    authDomain: 'calorie-calculator-40ou.firebaseapp.com',
    storageBucket: 'calorie-calculator-40ou.appspot.com',
  );
}
